[ Merge after PR #1 ] Add Hack CU IV date & location!!
HackCU/events pull request #2
Opened 2017-12-20 05:34 UTC by elliotwhitehead

## Description
A few sentences describing the overall goals of the pull request's commits.

## Related Issues
Link to any issues that are relevant to this PR. This could be an issue this PR fixes.

## Some questions
- [ ] I read the contributing guidelines
- [ ] I'm adding a new event/footer link
- [ ] I'm editing an existing event/footer link
- [ ] I'm adding a new feature/fixing a bug

If you answered No to question 1, go back and read the [instructions](.github/CONTRIBUTING.md) carefully.

## Additional Notes
Do you want to add anything else? We :heart: to hear your opinions!

2017-12-20 17:15 UTC, AparaV requested changes
Let's wait until we deploy the registration backend. Then we can keep the entire update of the event (along with the description) to the same PR.

Or, you can update the description now (not waiting on the applications to go live) and merge it.

2017-12-20 17:15 UTC, AparaV commented on _data/events.yml
> +  location: SEEC Building (East Campus)
Can we add a hyperlink to a map or something? That would make it easier for people who are not familiar with the building (like me!) to find it.

2017-12-20 17:15 UTC, AparaV commented on _data/events.yml
>    line: Subscribe to be the first to know when applications go live.
I would suggest that we wait until @casassg deploys the backend for public. And then update the description also in the same PR

2017-12-20 17:18 UTC, AparaV commented on _data/events.yml
> +  location: SEEC Building (East Campus)
Never mind, just realized that we have a link to the actual website where we will soon have the map of the venue

2017-12-22 18:54 UTC, casassg requested changes
looks good, let's also update the image preview

2017-12-22 18:54 UTC, casassg commented on _data/events.yml
>    image-url: assets/img/hackcu.png
Update image to something like this: 

https://beta.hackcu.org/assets/images/ogimage870x450.png

2018-01-05 01:17 UTC, casassg approved these changes

2018-01-05 03:58 UTC, AparaV approved these changes

2018-01-05 03:59 UTC, merged